use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::features::{
        case_notes_commands, example_feature_commands, notes_commands, notifications_commands,
        preferences_commands, quick_pane_commands, recovery_commands,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        // Preferences feature
        preferences_commands::greet,
        preferences_commands::load_preferences,
        preferences_commands::save_preferences,
        // Notifications feature
        notifications_commands::send_native_notification,
        // Recovery feature
        recovery_commands::save_emergency_data,
        recovery_commands::load_emergency_data,
        recovery_commands::cleanup_old_recovery_files,
        // Quick pane feature
        quick_pane_commands::show_quick_pane,
        quick_pane_commands::dismiss_quick_pane,
        quick_pane_commands::toggle_quick_pane,
        quick_pane_commands::get_default_quick_pane_shortcut,
        quick_pane_commands::update_quick_pane_shortcut,
        // Example feature (template)
        example_feature_commands::load_example_data,
        example_feature_commands::save_example_data,
        // Documentation feature - case notes
        case_notes_commands::load_case_note,
        case_notes_commands::save_case_note,
        // Documentation feature - notes
        notes_commands::load_note,
        notes_commands::save_note,
        notes_commands::list_notes,
        notes_commands::delete_note,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
